# Generated by Django 4.2.26 on 2025-12-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_cadastro',
            new_name='criado_em',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Pessoal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio')], default='clt', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
