# Generated by Django 4.2.26 on 2025-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_rename_data_cadastro_funcionario_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Desligamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desligado',
            field=models.BooleanField(default=False, verbose_name='Colaborador Desligado?'),
        ),
    ]
