# Generated by Django 4.2.26 on 2025-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_funcionario_data_desligamento_funcionario_desligado'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desc_assist_medica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Assist. Médica'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desc_assist_odonto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Assist. Odonto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desc_vale_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Vale Alimentação'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desc_vale_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Vale Transporte'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lotacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lotação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='Salário Base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio')], default='clt', max_length=20),
        ),
    ]
