# Generated by Django 4.2.26 on 2025-12-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_funcionario_agencia_funcionario_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('V', 'Vencimento'), ('D', 'Desconto')], max_length=1)),
                ('incide_inss', models.BooleanField(default=True)),
                ('incide_irrf', models.BooleanField(default=True)),
                ('incide_fgts', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_assist_medica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_assist_odonto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_vale_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_vale_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desligado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='lotacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base Atual'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('saida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('saida_2', models.TimeField(blank=True, null=True)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('atrasos', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.eventofolha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='human_resources.funcionario')),
            ],
            options={
                'verbose_name': 'Lançamento Mensal',
                'verbose_name_plural': 'Lançamentos Mensais',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCargoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateField()),
                ('cargo_anterior', models.CharField(max_length=100)),
                ('cargo_novo', models.CharField(max_length=100)),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('filho', 'Filho(a)'), ('conjuge', 'Cônjuge'), ('pais', 'Pais')], max_length=20)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('irrf', models.BooleanField(default=True, verbose_name='Abate no IRRF?')),
                ('salario_familia', models.BooleanField(default=True, verbose_name='Recebe Sal. Família?')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='human_resources.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ControleFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_aquisitivo_inicio', models.DateField()),
                ('periodo_aquisitivo_fim', models.DateField()),
                ('dias_direito', models.IntegerField(default=30)),
                ('dias_gozados', models.IntegerField(default=0)),
                ('saldo_dias', models.IntegerField(default=30)),
                ('pago', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.funcionario')),
            ],
        ),
    ]
