# Generated by Django 4.2.26 on 2025-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_eventofolha_funcionario_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/', verbose_name='Foto 3x4'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/qr_codes/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_assist_medica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Assist. Médica (Fixo)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_assist_odonto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Assist. Odonto (Fixo)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_vale_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Vale Alimentação (Fixo)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desc_vale_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Vale Transporte (Fixo)'),
        ),
    ]
